const PRIVS_ENUM = {
    IS_OWNER: "IS_OWNER",
    IS_FRIEND: "IS_FRIEND",
    IS_LGGED: "IS_LOGGED",
    IS_NOT_OWNER: "IS_NOT_OWNER",
    IS_NOT_FRIEND: "IS_NOT_FRIEND"
};
export default PRIVS_ENUM;
