/*
 * action types
 */

export const LOADER_ACTIONS = {
    SET_INITIAL_ACTION: "SET_INITIAL_ACTION",
    SET_BODY_ACTION: "SET_BODY_ACTION",
    SET_CONTAINER_ACTION: "SET_CONTAINER_ACTION",
    FINISH_INITIAL_ACTION: "FINISH_INITIAL_ACTION",
    FINISH_BODY_ACTION: "FINISH_BODY_ACTION",
    FINISH_CONTAINER_ACTION: "FINISH_CONTAINER_ACTION"
};
