import { QueryList } from "justshare-shared";
import { ActionsGen } from "../../../App/index";

const FITLER_SEARCH_ACTIONS = {
    SEARCH_ITEM_FETCH: ActionsGen(QueryList.Item.SEARCH_ITEM),
    SET_SEARCH_PARAMS: "SET_SEARCH_PARAMS",
    SET_CATEGORIES_SEARCH: "SET_CATEGORIES_SEARCH",
    ON_INIT_SEARCH: "ON_INIT_SEARCH",
    ON_MAP_INIT: "ON_MAP_INIT",
    SET_COORDINATS: "SET_COORDINATS",
    SET_CAT_ABOVE_PIN: "SET_CAT_ABOVE_PIN",
    SET_CATEGORY_OPTIONS:"SET_CATEGORY_OPTIONS",
    MOUNT_INSTANCE_OF_ENGINE:'MOUNT_INSTANCE_OF_ENGINE',
    UNMOUNT_INSTANCE_OF_ENGINE:'UNMOUNT_INSTANCE_OF_ENGINE',
    GET_CATEGORIES_TYPE_FETCH: ActionsGen(QueryList.CategoryOptions.GET_OPTIONS_TYPE),

};

export default FITLER_SEARCH_ACTIONS;
