import { NOTIFICATIONS_ACTIONS } from "../../../../App/Reducers/Notifications/actions";

const AUTHORIZE_USER_ACTIONS = {
    SET_NOTIFICATION_GLOBAL: NOTIFICATIONS_ACTIONS.SET_NOTIFICATION_GLOBAL
};

export default AUTHORIZE_USER_ACTIONS;
