const MAP_SEARCH_ACTIONS = {
    SET_COLOR_FOR_CATEGORIES: "SET_COLOR_FOR_CATEGORIES",
    SET_CATEGORIES_NEAR_THE_PIN: "SET_CATEGORIES_NEAR_THE_PIN",
    SET_CURRENT_ELEMENT: "SET_CURRENT_ELEMENT",
    SET_POSITION_CENTER: "SET_POSITION_CENTER",
    CLEAN_ITEMS: "CLEAN_ITEMS",
    ON_MAP_INIT: "ON_MAP_INIT",
    SET_COORDINATS: "SET_COORDINATS",
    SET_ACTIVE_ELEMENT: "SET_ACTIVE_ELEMENT"
};

export default MAP_SEARCH_ACTIONS;
